### PR TITLE
bump version 0.6.4

### PR DESCRIPTION
**Pull request by JackDanger**
So much fun new stuff to play with!

### CODE REVIEW

**Comment by lfittl** [comment]
@JackDanger I'll make a new published release of 0.6.3 before merging this - but could you do a `bundle install` so the gemspec has the correct version too? :bow:

**Comment by JackDanger** [comment]
> but could you do a bundle install so the Gemfile.lock has the correct version too?

Done!

**Comment by JackDanger** [comment]
@lfittl How about a release of 0.6.4? I'm hoping to demo some of the new pg_query features tomorrow and I'd love to have my gem (https://github.com/jackdanger/hsql) depending on the released gem and not some internal fork. Thanks!

**Comment by lfittl** [comment]
Yes! I'll see that I can fit that in later today :)

**Comment by lfittl** [comment]
@JackDanger Done!

Let me know how it went - hsql looks nice :)

**Pull request merged**
