### PR TITLE
Add support for ORDER/GROUP BY, HAVING, and booleans in WHERE.

### PR DESCRIPTION
**Pull request by jcoleman**

### CODE REVIEW

**Comment by lfittl** [comment]
@jcoleman Excellent, thanks for thinking of these & the PR.

Ready to merge once the rubocop nitpicks are fixed (see Travis).

**Comment by jcoleman** [comment]
@lfittl Fixed.

**Comment by jcoleman** [comment]
@lfittl If we could get a new release soon that'd be great. We vendor our bundle installs and this bug: https://github.com/bundler/bundler/issues/4106 is making it so we can't use a git ref in our Gemfile.

**Comment by lfittl** [comment]
@jcoleman Sure thing - I have one more change I want to get in, but I'll try to wrap it up today :)

**Comment by jcoleman** [comment]
@lfittl Just checking back here again to see if you have any updates. Apologies for bugging you again, but we can't merge in our updated code that relies on this until a new version is pushed. Thanks!

**Comment by lfittl** [comment]
@jcoleman Apologies, I got side-tracked with something else. I've released the current master as 0.11.0 to make your life easier :)

Out of curiosity, what are you using pg_query for?

**Comment by jcoleman** [comment]
@lfittl Thanks! We're using it in a custom rspec matcher to verify that certain code only accesses certain tables.

**Comment by lfittl** [comment]
@jcoleman Neat, thats actually a great use case I hadn't thought of :)

Would be happy to add that to the README as an example of what you can do with the parser, in case its open-source!

**Comment by jcoleman** [comment]
It's currently not open source, but I can look into seeing if we might be able to go that route.

**Comment by lfittl** [comment]
@jcoleman Cool, no rush - if you end up releasing it let me know, I could see this being useful to others :)

**Pull request merged**
