### PR TITLE
Deparsing CREATE TABLE queries

### PR DESCRIPTION
**Pull request by JackDanger**
Includes support for most type aliases. Examples mostly pulled from the
postgresql docs.

@lfittl One more for you! :)

### CODE REVIEW

**Comment by lfittl** [comment]
Great - love it :)

**Comment by lfittl** [comment]
Merged with two rubocop fixes: https://github.com/lfittl/pg_query/commit/bafe7b5310a0eb16dbf6fd902fcace49175c9a47

**Comment by JackDanger** [comment]
Oh, thank you! Ooops, I totally forgot to run Rubocop.

**Comment by lfittl** [comment]
No worries - I need to figure out how to get Codeship/TravisCI running rspec+rubocop on the PRs here :)

**Comment by JackDanger** [comment]
> No worries - I need to figure out how to get Codeship/TravisCI running rspec+rubocop on the PRs here :)

Or you could use the gratitude that I have for your incredible work on this project to just have me do it :)
#21

**Comment by JackDanger** [comment]
FYI: I'm attempting to get this to work for 100% of the ETLs in use at Square so I suspect the deparser will be quite exhaustive by the time I'm done.

**Comment by lfittl** [comment]
Nice!

Thanks for taking the time, I'll get that setup in a moment :)

**Pull request merged**
