### PR TITLE
Update JSON gem dependency for Ruby 2.4

### PR DESCRIPTION
**Pull request by merqlove**
Subj

### CODE REVIEW

**Comment by lfittl** [comment]
@merqlove Thanks for the PR!

I haven't updated to Ruby 2.4 yet - whats the reason we have to avoid using a newer version of the json gem?

**Comment by merqlove** [comment]
Hi @lfittl, a lot of gems depended on '~> 1.x'. Too popular gem.

**Comment by lfittl** [comment]
Ah, now I see what happened - thanks for the explanation :)

**Comment by flaviocamilo** [comment]
Any schedule for this to be released? Thanks!

**Comment by lfittl** [comment]
@flaviocamilo Thanks for the reminder, released as 0.11.4 today.

**Comment by flaviocamilo** [comment]
Thanks!

**Pull request merged**
