### PR TITLE
Deparse COPY statement

### LINKED ISSUE #89: deparse fails on CopyStmt
`print PgQuery.parse("COPY t (c1) FROM STDIN").deparse` blows up

### PR DESCRIPTION
**Pull request by herwinw**
This fixes #89

### CODE REVIEW

**Comment by lfittl** [comment]
Thanks!

**Comment by benchub** [comment]
Thanks herwinw, this fixes all my outstanding issues with pg_query! 

lfittl, any chance you could make a new gem?

**Comment by herwinw** [comment]
given his reaction in #109 I'd expect  new release soon :)

**Comment by lfittl** [comment]
@herwinw Done! Thanks again for all your contributions :)

**Pull request merged**
