### PR TITLE
[Work in Progress] Generate deparser files from DSL

### PR DESCRIPTION
**Pull request by lfittl**
This rewrites the deparser output logic to be in a DSL that can more easily be translated into other frameworks/languages.

Right now this is experimental, the language is a bit ugly, and the generator needs tests - but feedback welcome.

### CODE REVIEW

**Comment by lfittl** [comment]
@zhm This is the approach I'm currently thinking about to make the deparsing accessible for other languages.

Would an approach like this work for you?

You could generate the appropriate node.js files using either the [JSON file](https://github.com/lfittl/pg_query/blob/deparser-generator/deparser.json), or we just add another generator for basic Javascript in the repo (like https://github.com/lfittl/pg_query/blob/deparser-generator/generate_deparse_ruby.rb)

Note: This PR is in the Ruby library for simplicity right now, but I'll move it to the libpg_query repository later

**Comment by zhm** [comment]
I think this is awesome! Ultimately I think I'm mostly concerned with correctness + robustness of the results. I think it would be great to have a fully data-driven definition of the deparsing logic.

Over the last bit I ported the ruby deparser to coffeescript for a project I'm working on. I would gladly use a DSL-generated one though.

In the process of working on the js deparser, I've come to find out that the deparser is quite complex, and handling all of the rules of the language in the DSL might be very time-consuming to build out.

My deparser is [here](https://github.com/zhm/pg-query-parser/blob/master/src/deparser.coffee).

I'm only concerned with SELECT statements, so I haven't implemented any of the data-modifying stuff. There are _many_ things fixed from the deparser in this gem.

The test suite in the js deparser runs *all* of the `SELECT` statements from the real [Postgres test suite](https://github.com/zhm/pg-query-parser/tree/master/test/fixtures/upstream), and it successfully parses and deparses ~7000 different `SELECT` statements. For the most accurate deparsing, I'm comparing the parse tree of the original statement with the parse tree of the deparsed statement and asserting that they're identical (except for the `location` key). A similar approach for a test suite for the DSL-generated one might be good too.

This is looking promising!

**Comment by lfittl** [comment]
@zhm Nice, well done on the coffeescript deparser - that must have been quite some work :)

100% agree that the real PostgreSQL test suite is the way to go - I'd also love to generate some basic coverage information using the node type information (i.e. which types and fields are tested).

I'm going to focus on using the DSL-based approach to get the Ruby and Go libraries on the same page, maybe we can revisit how/if we can merge the approaches once that is done. I'll keep you in the loop.

Previously @JackDanger was also interested in potentially porting pg_query to Python (he wrote most of the Ruby deparser logic), so ideally we find some way where the logic does not diverge too much.

**Comment by zhm** [comment]
My thinking was it might be easier/faster to build out a full DSL if we have a full deparser. It's extremely time-consuming to constantly cross-reference the C headers/example statements/logic/tests to get everything just right. I did encounter a postgres feature I didn't even know existed - "frame options" on the `WINDOWDEF` nodes. In fact, `WINDOWDEF` nodes are a bit of a pain and I don't think I fully understand the grammar because deparsing them is kinda hacky.

I don't claim to fully understand everything about the syntax, and the logic in the js deparser definitely needs some love, but I was mostly focused on getting the tests to pass before trying to clean it up.

I did notice another edge case that I think requires a change in the native code to fix.

```sql
SELECT 999999999999999999999::numeric/1000000000000000000000;
```

and

```
SELECT 4790999999999999999999999999999999999999999999999999999999999999999999999999999999999999 * 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999;
```

These are obviously absurd statements, but they're in the real postgres test suite and currently aren't possible to make symmetric with the deparser.

One other tricky thing is getting the output of the deparser to be "friendly". For example, ideally the output of the deparser contains as few parenthesis as absolutely necessary to make the parse trees symmetric. But it seems like that might require more contextual information. But I might be wrong, maybe it just means I need to understand the grammar a little better ;)

**Comment by lfittl** [comment]
@zhm Unfortunately you are right regarding context - there is some basic steps around this for the `AEXPR` nodes in the Ruby deparser, but there is lots more ground to cover.

I'll see that I dig into that parser inconsistency tonight & fix that in libpg_query.

Btw, also sent you a quick email - maybe we can setup a time to chat so we're doing this stuff efficiently and me merging things doesn't hold you back :)

**Comment by lfittl** [comment]
Closing this for now, as this isn't the latest idea on how to approach it anymore.

**Pull request closed without merging**
